# Servidor
server.port=8080

# Banco
spring.datasource.url=jdbc:mysql://localhost:3306/techweek?useSSL=false&serverTimezone=America/Sao_Paulo&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=root

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Thymeleaf
spring.thymeleaf.cache=false

# Upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
app.upload.dir=D:/Usuarios/joaov/Downloads/Spring/siteFacul/techweek/uploads/curriculos

# E-mail Brevo
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=a97b01001@smtp-brevo.com
spring.mail.password=TME5Lm4B0qwC9jcn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
app.mail.remetente=iitechweek2026@gmail.com