# Servidor
server.port=${PORT:8080}

# Banco
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Thymeleaf
spring.thymeleaf.cache=false

# Upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
app.upload.dir=${APP_UPLOAD_DIR:/tmp/uploads}

# E-mail Brevo
brevo.api.key=${BREVO_API_KEY}
app.mail.remetente=${MAIL_REMETENTE:iitechweek2026@gmail.com}